version: '3'

services:
  mongo:
    image: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
    volumes:
      - mongo
  mongo-express:
    image: mongo-express
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: root
      ME_CONFIG_BASICAUTH_USERNAME: pp
      ME_CONFIG_BASICAUTH_PASSWORD: pp
    depends_on:
      - mongo
    ports:
      - '8080:8081'
  backend:
    restart: always
    depends_on:
      - mongo
    build: ./server
    external_links:
      - mongo
    ports:
      - '3000:80'
  frontend:
    restart: always
    depends_on:
      - backend
    build: .
    ports:
      - '80:80'
